<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mod</string>
	</array>
	<key>name</key>
	<string>NMODL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>:.*</string>
			<key>name</key>
			<string>comment.line.nmodl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nmodl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(TITLE).*</string>
			<key>name</key>
			<string>comment.line.nmodl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(COMMENT)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nmodl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(ENDCOMMENT)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.nmodl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>INDEPENDENT|COMMENT|ENDCOMMENT|TITLE|PARAMETER|ASSIGNED|CONSTANT|STATE|DERIVATIVE|INITIAL|BREAKPOINT</string>
			<key>name</key>
			<string>entity.name.function.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>LOCAL|PROCEDURE|KINETIC|FUNCTION|DEFINE|NEURON|BEFORE|AFTER|NET_RECEIVE|UNITSON|UNITSOFF|UNITS</string>
			<key>name</key>
			<string>entity.name.function.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>COMPARTMENT|SOLVE|STEADYSTATE|METHOD|SUFFIX|USEION|READ|WRITE|GLOBAL|RANGE</string>
			<key>name</key>
			<string>entity.name.function.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>LONGITUDINAL_DIFFUSION|LINEAR|NONLINEAR|SOLVE|POINT_PROCESS|NONSPECIFIC_CURRENT|ELECTRODE_CURRENT|STEADYSTATE|CONSERVE</string>
			<key>name</key>
			<string>entity.name.function.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>if|else</string>
			<key>name</key>
			<string>keyword.control.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>FROM|TO|TABLE|WITH</string>
			<key>name</key>
			<string>keyword.other.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|\/|\=|\'</string>
			<key>name</key>
			<string>keyword.operator.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+\.[0-9]+|\.[0-9]+|[0-9]+\.</string>
			<key>name</key>
			<string>constant.numeric.nmodl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.nmodl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nmodl</string>
	<key>uuid</key>
	<string>21634a46-8474-4890-9731-9fc45862c6e7</string>
</dict>
</plist>
